### ISSUE TITLE
CORS errors fetching BAI data with Basic authentication header

### ISSUE THREAD

**Issue by alexpreynolds** [GMOD/generic-filehandle#113]
I am trying to retrieve reads from a BAM file via the `bam-js` and `generic-filehandle` libraries.

The BAM and BAI files I am retrieving data from are behind a web server that uses Basic authentication.

My client initializes a `BamFile` object from the `bam-js` library:

```
if (!bamFiles[bamUrl]) {
  bamFiles[bamUrl] = new BamFile({
    bamUrl,
    baiUrl,
  });
  bamHeaders[bamUrl] = bamFiles[bamUrl].getHeader();
}
```

The `bamUrl` and `baiUrl` strings contain the Basic authentication credentials in their respective URLs. The native `fetch` call does not support credentials in the URL, so these are parsed out with the native JavaScript `URL` library and used to manually set up the `Authorization` header, as follows:

I forked `bam-js` and `generic-filehandle` and made modifications to `generic-filehandle` to add a Basic authentication header, if credentials are provided, e.g.:

https://github.com/alexpreynolds/bam-js/blob/reservoir-sampling/src/bamFile.ts#L153-L165

and behind that, in `RemoteFile`:

https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L99-L101

I get the following errors related to the BAI index file:

```
Access to fetch at 'https://example.com/foo.bam.bai' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

and:

```
Access to fetch at 'https://example.com/foo.bam.bai' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

These errors appear to result from the `try-catch` block executed in `generic-filehandle`'s `RemoteFile`:

https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L49-L84

However, the error seems unusual as I do have CORS headers configured.

To verify this, I used `curl` to get the headers and the BAI file directly, e.g.:

```
% curl --head -u username:password https://example.com/foo.bam.bai
HTTP/1.1 200 OK
Date: Tue, 07 May 2024 05:58:02 GMT
Server: ...
Strict-Transport-Security: max-age=31536000; includeSubDomains
Last-Modified: Mon, 29 Apr 2024 05:20:53 GMT
ETag: "155620-617356ad8834d"
Accept-Ranges: bytes
Content-Length: 1398304
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE, PUT
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range, Authorization
Access-Control-Allow-Credentials: true
Content-Type: application/octet-stream
Content-Encoding: dummy
```

The full `curl` request serves the BAI file in the provided link. The authentication token is present in debug output, as well, i.e.: `Authorization: Basic <base64-encoded-string>`.  

This token in the `curl` request matches the `Authorization` header I am adding to the requests in `generic-filehandle`.

As near as I can tell, I am passing in the correct authentication header, the server hosting BAM files is configured to serve related CORS headers, and I'm using a very recent version of Chrome (123.0.6312.107) — so I'm a bit unsure how to proceed.

I dug into some issues reported in another GMOD project, which may be related if they use the same `generic-filehandle` dependency:

 * https://github.com/GMOD/jbrowse/issues/1315
 * https://github.com/GMOD/jbrowse/issues/1091
 
Is there anyone who has encountered this error who might have advice on debugging this? I'm just not sure what else I can try.

**Comment by cmdcolin** [comment]
from a conceptual standpoint, sending credentials to another domain is a thing that your browser probably correctly identifies as a dangerous thing to do (you are sending your username and password across different domains, which is something that could lead to a compromise of user data if there was a simple e.g. XSS vulnerability on the page so it puts in particularly strict CORS rules for it

note1 https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials
```
"By default, in cross-origin fetch() or XMLHttpRequest calls, browsers will not send credentials."
```

note 2 https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
```
"Note: Access-Control-Allow-Origin is prohibited from using a wildcard for requests with credentials: 'include'. In such cases, the exact origin must be provided; even if you are using a CORS unblocker extension, the requests will still fail."
```

note 3 https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
```
To cause browsers to send a request with credentials included on both same-origin and cross-origin calls, add credentials: 'include' to the init object you pass to the fetch() method.
js

fetch("https://example.com", {
  credentials: "include",
});

```

so you'll want to add credentials:include to the fetch second argument, and then also you can't use Access-Control-Allow-Origin: *, it has to be the particular domain. you can set it dynamically on the server to be equal to the requesting referrer as one way to make it automatically allowed but i can't necessarily advise how that affects things from a security point of view :)


other note: you can probably accomplish this without forking generic-filehandle and bam-js. if you want i can make the example code for that. you can use the overrides field of the RemoteFile constructor to provide the credentials: true argument https://github.com/GMOD/generic-filehandle?tab=readme-ov-file#options and then you can make bam-js accept those RemoteFile objects via bamFilehandle and baiFilehandle https://github.com/gmod/bam-js

**Comment by alexpreynolds** [comment]
Thanks very much for the detailed response.

Unfortunately, I added `credentials: 'include'` to the fetch request, and I changed the server CORS header to be specific about the origin host and port, but I still saw the same CORS error.

I am now adding the `credentials` in several locations, before where `fetch` is called:

https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L61-L65
https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L80-L85
https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L124-L127
https://github.com/alexpreynolds/generic-filehandle/blob/methylation/src/remoteFile.ts#L208-L212

In the last case, I used console to inspect the contents of the `init` object passed to `fetch`, and it typically looks like the following, to verify that this option is set:

```
{
  "headers": {
    "Authorization":"Basic <b64-string>"
  },
  "method":"GET",
  "redirect":"follow",
  "mode":"cors",
  "credentials":"include"
}
```

My test server is configured to respond with these CORS-specific headers for the test BAM file I am trying to request reads from:

```
Header add Access-Control-Allow-Origin http://localhost:3000
Vary Origin
Header add Access-Control-Allow-Methods "GET, POST, OPTIONS, DELETE, PUT"
Header add Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Range, Authorization"
Header add Access-Control-Allow-Credentials true
```

The origin is set to the localhost and port number of the test client app making the request.

> other note: you can probably accomplish this without forking generic-filehandle and bam-js. if you want i can make the example code for that. you can use the overrides field of the RemoteFile constructor to provide the credentials: true argument https://github.com/GMOD/generic-filehandle?tab=readme-ov-file#options and then you can make bam-js accept those RemoteFile objects via bamFilehandle and baiFilehandle https://github.com/gmod/bam-js

I would appreciate seeing an example of this! 

Along with bam-js, I also use `RemoteFile` to retrieve data from indexedfasta-js and bbi-js libraries, and there can be scenarios where I may need to also authenticate access. Perhaps there is something incorrect with the modifications I am making to generic-filehandle.

Thanks again for all your help!

**Comment by alexpreynolds** [comment]
Thanks for the example code!

While the demo client and server you provided do work, I still am unable to get authenticated requests working when hitting a live server.

I'm using code that calls `bam-js` routines outside of an `async`-`await` context, so I put your modifications into the following forked-branch of `bam-js`, to send overrides to the `RemoteFile` filehandle constructor in `generic-filehandle`:

https://github.com/alexpreynolds/bam-js/blob/rs-v2p0p2-051224/src/bamFile.ts#L141-L163

When `bamUrl` and `baiUrl` are provided to `BamFile`, and those URLs contain credentials, they are stripped out and used to make an `Authorization` header.

I believe these are the same modifications as in:

https://github.com/cmdcolin/bam_fetch_auth_file/blob/main/src/App.tsx#L67-L87

The difference is that I modify the URL to remove credentials, as the fetch implementation will otherwise return an error complaining about credentials in the URL.

I set the origin to my localhost and port:

```
Header add Access-Control-Allow-Origin http://localhost:3000
```

Despite with the overrides and the custom origin, the preflight check appears to remain unauthorized:

![devTools 051224](https://github.com/GMOD/generic-filehandle/assets/33584/94190a95-9257-4fad-97ea-e0978816910c)

The request is stuck on the same refetch here:

https://github.com/GMOD/generic-filehandle/blob/master/src/remoteFile.ts#L42-L64

As a sanity check, if I disable the auth requirement on the server and do not pass credentials in the URL, then I am able to access the test file.

**Comment by alexpreynolds** [comment]
I'm not sure if the following is a good workaround, but the following Apache directive in an `.htaccess` file disables the requirement to authenticate the OPTIONS preflight request:

```
<LimitExcept OPTIONS>
  Require valid-user
</LimitExcept>
```

Setting the origin is still required, e.g.:

```
Header add Access-Control-Allow-Origin http://localhost:3000
```

I'm not sure about the security implications of this.

I tried digging into the demo Expressjs server response to see how unauthenticated preflight OPTIONS requests are handled, but Chrome's network panel didn't seem to show a preflight OPTIONS request available to inspect.

**Comment by cmdcolin** [comment]
>While the demo client and server you provided do work, I still am unable to get authenticated requests working when hitting a live server.

unclear what you mean by a live server. the demo that I provided allows you to edit the URL of the bam and bai files and the username and password in the textboxes, so you can try pointing it at your other live server


>I'm using code that calls bam-js routines outside of an async-await context

this is a somewhat curious thing to say. i could elaborate but you can create async/await contexts wherever you want, so don't let that limit you :) you might already be aware of such things but here are some examples of different ways of doing this

```
// this is an actual async function
async function doAsyncFetch() {
  const result = await fetch("http://stuff.com/resource.json");
  const data = await result.json();
  return data;
}

function thisIsNotAnAsyncFunction() {
  doFetch(); // you can just call this which fires off the request and forgets about the error handling and result of this function
}

function thisIsNotAnAsyncFunction2() {
  // use "promise chaining" to handle the async result and error handling
  doFetch()
    .then((result) => {
      console.log("doFetch returned: ", result);
    })
    .catch((e) => {
      console.error("caught the error: ", e);
    });
}

function thisIsNotAnAsyncFunction3() {
  // use immediately invoked function expression ("IIFE") to get async await syntax inside a non-async function
  (async () => {
    try {
      const result = await doFetch();
      console.log("doFetch returned: ", result);
    } catch (e) {
      console.error("caught the error: ", e);
    }
  })();
}

```

i could try to address the other things you bring up if there are still any concerns. i would indeed not use the username:password in the URL though. it is perhaps allowed in some contexts by HTTP Basic Auth system but i think it is blocked by many browsers as old/deprecated in many contexts

**Comment by alexpreynolds** [comment]
> i would indeed not use the username:password in the URL though. it is perhaps allowed in some contexts by HTTP Basic Auth system but i think it is blocked by many browsers as old/deprecated in many contexts

Thanks, makes sense!
