### ISSUE TITLE
module should export a `GenericFilehandle` type

### ISSUE THREAD

**Issue by rbuels** [GMOD/generic-filehandle#75]
When writing typescript that uses generic-filehandle, it would be convenient to have access to the GenericFilehandle interface, so you can use it to write polymorphic function signatures

**Comment by cmdcolin** [comment]
I think there should be a GenericFilehandle base class that is exported

If I do

```
mkdir test
yarn init

```



...
yarn add generic-filehandle

vim index.ts
```
import { GenericFilehandle } from "generic-filehandle";

function getReader(file: GenericFilehandle) {
  file.readFile();
}
```

No typescript complaints for me

**Comment by cmdcolin** [comment]
Note: It is technically an interface type from typescript instead of a true base class

**Comment by cmdcolin** [comment]
If you have generic-filehandle installed you can inspect node_modules/generic-filehandle/dist/filehandle.d.ts

**Comment by cmdcolin** [comment]
Note that you might, in your client library, also want to install @types/node because otherwise it won't recognize the type Buffer and might say the return types are `any`, but once @types/node is installed, you will see file.readFile() produce Promise<Buffer|string>

**Comment by cmdcolin** [comment]
cc @mattmorgan6 let me know if I can help with any of this type stuff :)

**Comment by mattmorgan6** [comment]
It's not a blocking issue or anything but kind of strange. Thanks for the help!
